## Task 1: Array Basics (Numpy)

In [2]:
import numpy as np # import numpy library

## 1. Create Arrays

#### ● Generate the following numpy arrays:
1. A 1D array of integers from 0 to 9.

In [5]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array3 = np.linspace(0, 9, 10, dtype=int) # from 0 to 9 .. 10 values , type is int  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# array3 = np.linspace(0, 9, 10) # without type output is array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. A 3x3 matrix of random integers between 1 and 100.

In [9]:
# random 3D array
matrix = np.random.randint(1, 101, size=(3, 3)) # [ 1, 101 [ to include 100 
matrix

array([[71, 82, 74],
       [49,  9, 90],
       [20, 60, 14]])

In [10]:
# fixed 3D array
matrix2 = np.array([[1, 72, 45], [10, 99 , 17] ,[44, 54 , 61]])
matrix2

array([[ 1, 72, 45],
       [10, 99, 17],
       [44, 54, 61]])

## 2. Reshape Arrays


#### ● Reshape the 1D array from (1.1) into a 2D array with 2 rows and 5 columns.

In [13]:
array_to_2D = np.resize(array, (2, 5)) #using resize function from np
array_to_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
array2_to_2D = array.reshape(2, 5)  #using reshape method
array2_to_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 3. Array Attributes

### Display the following attributes of any one array:
○ Shape
○ Size
○ Data type

##### applay on  1D array

In [18]:
# Shape
array.shape

(10,)

In [19]:
# Size
array.size

10

In [20]:
# Data type
array.dtype

dtype('int32')

##### applay on  3D array/matrix

In [22]:
# Data type
matrix.shape

(3, 3)

In [23]:
# Data type
matrix.size

9

In [24]:
# Data type
matrix.dtype

dtype('int32')

## Task 2: Data Manipulation (Pandas)

In [26]:
import pandas as pd # import pandas library

### 1. DataFrame Creation
- Create a pandas DataFrame with random data (5 rows and 3 columns)
- Label the columns as "A," "B," and "C."

In [28]:
# Create random data
data = np.random.randint(100, size=(5, 3)) # 5 rows , 3 columns
data

array([[74, 15, 81],
       [80, 78, 94],
       [ 2, 24, 94],
       [81, 41, 99],
       [48,  4, 81]])

In [29]:
# OR
data = 100 * np.random.rand(5, 3)
data

array([[59.65403989,  6.34878857,  6.14784416],
       [64.50294837, 47.65897669, 11.13012175],
       [88.39713628, 10.23538671, 79.81352948],
       [46.33795202, 26.31284988, 25.61833114],
       [38.12851601, 26.96804538, 94.73302359]])

In [30]:
# Create DataFrame with random created data
df = pd.DataFrame(data) 
df

0          1          2
0  59.654040   6.348789   6.147844
1  64.502948  47.658977  11.130122
2  88.397136  10.235387  79.813529
3  46.337952  26.312850  25.618331
4  38.128516  26.968045  94.733024

In [31]:
df.columns = ['A', 'B', 'C'] # or can directly df = pd.DataFrame(np.random.rand(5, 3) , columns=['A', 'B', 'C'])
df

A          B          C
0  59.654040   6.348789   6.147844
1  64.502948  47.658977  11.130122
2  88.397136  10.235387  79.813529
3  46.337952  26.312850  25.618331
4  38.128516  26.968045  94.733024

### 2. Basic Operations
- Display the first two rows of the DataFrame
- Calculate the mean of each column
- Add a new column "D" which is the sum of columns "A" and "B"


In [33]:
df.head(2) # using head method

A          B          C
0  59.654040   6.348789   6.147844
1  64.502948  47.658977  11.130122

In [34]:
df.loc[[1, 2]]  # using loc

A          B          C
1  64.502948  47.658977  11.130122
2  88.397136  10.235387  79.813529

In [35]:
df.mean() # for all column 

A    59.404119
B    23.504809
C    43.488570
dtype: float64

In [36]:
df.A.mean() # mean for A column using .A to specify column

59.40411851215987

In [37]:
df['B'].mean() # mean for B column using ['B'] to specify column

23.50480944819749

In [38]:
df['C'].mean()

43.48857002515342

In [39]:
df['D'] = df['A']+df['B'] # creat new D column = sum of A and B

In [40]:
df

A          B          C           D
0  59.654040   6.348789   6.147844   66.002828
1  64.502948  47.658977  11.130122  112.161925
2  88.397136  10.235387  79.813529   98.632523
3  46.337952  26.312850  25.618331   72.650802
4  38.128516  26.968045  94.733024   65.096561

### 3. Filtering and Sorting
- Filter rows where column "A" values are greater than 50
- Sort the DataFrame by column "C" in descending order.

In [42]:
filter_df = df[df['A'] > 50] 
filter_df

A          B          C           D
0  59.654040   6.348789   6.147844   66.002828
1  64.502948  47.658977  11.130122  112.161925
2  88.397136  10.235387  79.813529   98.632523

In [43]:
sorted_by_C = df.sort_values(by='C', ascending=False) # تنازلي
sorted_by_C

A          B          C           D
4  38.128516  26.968045  94.733024   65.096561
2  88.397136  10.235387  79.813529   98.632523
3  46.337952  26.312850  25.618331   72.650802
1  64.502948  47.658977  11.130122  112.161925
0  59.654040   6.348789   6.147844   66.002828

## Task 3: Numerical Computations (Numpy)

### 1. Element-Wise Operations
- Create two 1D arrays of the same size with random integers
- Perform addition, subtraction, and multiplication on the arrays


In [46]:
# Create two 1D arrays with random integers
array1 = np.random.randint(100, size=10)
array2 = np.random.randint(100, size=10)
array1, array2

(array([44, 66, 42,  9, 23, 23, 85,  3, 88, 78]),
 array([26,  0, 82, 89, 66, 99, 34, 72, 42, 66]))

In [47]:
# Addition
addition = array1 + array2
print("Addition Arrays:", addition)

Addition Arrays: [ 70  66 124  98  89 122 119  75 130 144]


In [48]:
# Subtraction
subtraction = array1 - array2
print("Subtraction Arrays:", subtraction)

Subtraction Arrays: [ 18  66 -40 -80 -43 -76  51 -69  46  12]


In [49]:
# Multiplication
multiplication = array1 * array2
print("Multiplication Arrays:", multiplication)

Multiplication Arrays: [1144    0 3444  801 1518 2277 2890  216 3696 5148]


### 2. Aggregate Functions
- Calculate the mean, sum, and standard deviation of a 1D array

In [51]:
mean = np.mean(array1) # using mean method
print("Mean:", mean)

Mean: 46.1


In [52]:
sum = np.sum(array1) # using sum 
print("Sum:", sum)

Sum: 461


In [53]:
std = np.std(array1) #using std
print("Standard Deviation:", std)

Standard Deviation: 30.008165555395085


### 3. Matrix Multiplication
- Create a 2x3 matrix and a 3x2 matrix
- Perform matrix multiplication using np.dot().

In [55]:
# 2x3 matrix
matrix = np.random.randint(100, size=(2, 3))
matrix

array([[ 6, 61, 24],
       [78,  0,  5]])

In [56]:
# 3x2 matrix
matrix_2 = np.random.randint(100, size=(3, 2))
matrix_2

array([[51, 33],
       [36, 20],
       [79, 62]])

In [57]:
# Matrix multiplication
matrix_mult= np.dot(matrix, matrix_2)
matrix_mult

array([[4398, 2906],
       [4373, 2884]])

In [58]:
# Matrix multiplication
matrix_mult= np.dot(matrix_2, matrix)
matrix_mult

array([[2880, 3111, 1389],
       [1776, 2196,  964],
       [5310, 4819, 2206]])

## Task 4:

### 1. Temperature Analysis
-  Create a 1D array of 7 temperatures (one for each day of the week).
Find:
1. The average temperature.
2. Days with temperatures above the weekly average.

In [61]:
# Create a 1D array of 7 temperatures
temperatures = np.array([37.5, 37.5, 25.4, 16.8, 24.4, 16.6, 23.3])
temperatures

array([37.5, 37.5, 25.4, 16.8, 24.4, 16.6, 23.3])

In [62]:
# average temperature
avg_temperature = np.mean(temperatures)
avg_temperature

25.928571428571427

In [63]:
# Days with temperatures above the weekly average
above_average_days = np.where(temperatures > avg_temperature)[0]
above_average_days

# Days of the week
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# Print each day and its corresponding temperature
for day in above_average_days:
    print(f"{days[day]}: {temperatures[day]}")

Monday: 37.5
Tuesday: 37.5


### 2. DataFrame Operations
- Using pandas, create a DataFrame with two columns:
1.  "Day" (Monday to Sunday)
2.  "Temperature" (use the numpy array from Task 4.1).
3.  Calculate the day with the highest temperature.

In [65]:
data = {
    "Day": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "Temperature": temperatures
}
df = pd.DataFrame(data)
df

Day  Temperature
0     Monday         37.5
1    Tuesday         37.5
2  Wednesday         25.4
3   Thursday         16.8
4     Friday         24.4
5   Saturday         16.6
6     Sunday         23.3

In [66]:
# highest temperature
max_temperature= df['Temperature'].max()
max_temperature

37.5

In [67]:
above_average_days = df['Temperature'] == max_temperature

# Print all days have max temperatures
for day, temp in df[above_average_days].iterrows():
    print(f"{temp['Day']}: {temp['Temperature']}")

Monday: 37.5
Tuesday: 37.5


In [68]:
# index of the highest temperature
max_temperature_id = df['Temperature'].idxmax()
# row with the higest temperature
df.loc[[max_temperature_id]]

Day  Temperature
0  Monday         37.5

### 3. Stock Price simulation
- Create a pandas DataFrame with random stock prices for 5 days
- Add a column to calculate the percentage change in price day-to-day

In [70]:
# Create random stock prices for 5 days
stock_prices = np.random.randint(1000, size=5)
# DataFrame
df = pd.DataFrame({"Day": ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday"], "Stock Price": stock_prices})
df

Day  Stock Price
0   Saturday          752
1     Sunday          409
2     Monday          548
3    Tuesday          945
4  Wednesday          605

In [71]:
#  percentage change in price day-to-day
df['Percentage Change'] = df['Stock Price'].pct_change() * 100 
# pct_change: Computes the fractional change from the immediately previous row by default
# Ex: Wednesday : The percentage change = (952−269/269)×100 ≈ 253.903346%
df

Day  Stock Price  Percentage Change
0   Saturday          752                NaN
1     Sunday          409         -45.611702
2     Monday          548          33.985330
3    Tuesday          945          72.445255
4  Wednesday          605         -35.978836

## Bonus Question:
### Multi-Dimensional Data Analysis

-  Create a 3D array representing sales data for 3 products over 4 weeks (rows) and 7
days per week (columns).

In [74]:
data = np.random.randint(100, size=(3, 4, 7)) # random sales data for 3 products over 4 weeks and 7 days per week
data

array([[[65, 86, 56, 40, 91, 16, 36],
        [59, 95, 88, 43,  3, 10, 84],
        [79, 27, 52, 46, 95, 88, 85],
        [15, 23, 25, 12, 60, 24,  7]],

       [[10, 67, 91, 14, 65, 79, 35],
        [32, 44, 22, 99, 60, 62, 12],
        [56, 50, 72, 50, 70, 14, 58],
        [92, 16, 14, 57, 75, 82, 27]],

       [[65, 84, 56, 99, 82, 21, 25],
        [ 3, 94, 74, 38, 29, 75,  8],
        [98, 43,  1, 98,  4, 69, 84],
        [64, 53, 22, 62, 76, 66, 24]]])

- Calculate the total sales for each product across all weeks and days.

In [76]:
total_sales_for_product = np.sum(data, axis=(1, 2))
# axis=1 weeks
# axis=2 days
total_sales_for_product

array([1410, 1425, 1517])

In [77]:
for i, total in enumerate(total_sales_for_product):
    print(f"Total sales for Product {i+1}: {total}")

Total sales for Product 1: 1410
Total sales for Product 2: 1425
Total sales for Product 3: 1517


- Determine the day with the highest sales for each product in the dataset.


In [79]:
sales_per_day_per_product = data.sum(axis=1) # Sales for Each Day Across All Days for Each Product
sales_per_day_per_product

array([[218, 231, 221, 141, 249, 138, 212],
       [190, 177, 199, 220, 270, 237, 132],
       [230, 274, 153, 297, 191, 231, 141]])

In [80]:
highest_sales_day_per_product = np.argmax(sales_per_day_per_product, axis=1)
highest_sales_day_per_product

array([4, 4, 3], dtype=int64)

In [81]:
for i, day in enumerate(highest_sales_day_per_product):
    print(f"highest sales for Product {i+1}: in Day {day+1}")

highest sales for Product 1: in Day 5
highest sales for Product 2: in Day 5
highest sales for Product 3: in Day 4


- Identify the week with the lowest total sales overall.

In [83]:
# Sum sales for each week across all products and days
total_sales_per_week = data.sum(axis=(0, 2))

total_sales_per_week

array([1183, 1034, 1239,  896])

In [84]:
# Find the week with the lowest total sales overall
lowest_sales_week = np.argmin(total_sales_per_week) + 1  # +1 to convert from 0-3 index to 1-4 index

# Print the week with the lowest total sales
print(f"Week with the lowest total sales overall: Week {lowest_sales_week}")

Week with the lowest total sales overall: Week 4
