# Imporing Libraries

In [1]:
import numpy as np
import pandas as pd

# Numpy functions and operations

Create an array of zeros with the specified length:

In [89]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Create an array of ones with the specified length:


In [90]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Create an array of specified number with the specified length

In [91]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Create an array of specified range (0 to end [exclusive]):

In [92]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array of specified range (start to end [exculsive]):

In [93]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

Create an array with specified steps in specified range (start, end, steps[number of elements]):

In [94]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Convert a list to a numpy array:

In [95]:
my_list = [1, 2, 3, 5, 7, 12]
my_array = np.array(my_list)
my_array

array([ 1,  2,  3,  5,  7, 12])

Selecting specific element in an array:

In [96]:
my_array = np.array([1, 2, 3, 4, 5])
second_element = my_array[1]
second_element

2

Selecting last element in an array:

In [97]:
last_element = my_array[-1]
last_element

5

Subsetting an array:

In [98]:
subset_array = my_array[1:4]
subset_array

array([2, 3, 4])

Creating 2D array:

In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 2D arrays opeartions:

In [100]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print()
print(arr2)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


Adding 2D arrays:

In [101]:
result = arr1 + arr2
print(result)

[[ 6  8]
 [10 12]]


Multiplying 2D arrays:

In [102]:
result = arr1 * arr2
print(result)

[[ 5 12]
 [21 32]]


#### Finding statistical calculations of 2D arrays:

Summation:

In [103]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
sum_val = np.sum(arr)
sum_val

21

Mean (Average) for rows:

In [104]:
mean_val = np.mean(arr, axis=0)
mean_val

array([2.5, 3.5, 4.5])

Mean (average) for columns:

In [105]:
mean_val = np.mean(arr, axis=1)
mean_val

array([2., 5.])

2D array of zeros:

In [106]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

2D array from 2D list:

In [107]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Accessing specific row:

In [108]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row = arr[1, :]
print(row)

[4 5 6]


In [109]:
row = arr[0, :]
print(row)

[1 2 3]


Accessing multiple rows:

In [110]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = arr[[0, 2], :]
rows

array([[1, 2, 3],
       [7, 8, 9]])

accessing array's rows:

In [111]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(n[0])
print(n[1])
print(n[2])

[1 2 3]
[4 5 6]
[7 8 9]


manipulating array's data:

In [112]:
n[0] = [12, 13, 14]
n

array([[12, 13, 14],
       [ 4,  5,  6],
       [ 7,  8,  9]])

accessing specific columns:

In [113]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
column = arr[:, 1]
print(column)

[2 5]


Accessing multiple columns:

In [115]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
columns = arr[:, [0, 2]]
columns

array([[1, 3],
       [4, 6],
       [7, 9]])

Accessing specific cells:

In [116]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
columns = arr[[0, 1], [0, 2]]
columns

array([1, 6])

Accessing first row:

In [117]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n[:, 0]

array([1, 4, 7])

Manipulating specific row:

In [118]:
n[:, 0] = [12, 13, 14]
n

array([[12,  2,  3],
       [13,  5,  6],
       [14,  8,  9]])

In [119]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(n[:, 0])

[1 4 7]


Accessing all 2D array:

In [120]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
n[:, 2] = [0, 1, 2]
n[:, 2]

array([0, 1, 2])

Generate random integer array values:

In [122]:
random_integers = np.random.randint(10, size=5)
print(random_integers)

[5 4 4 5 7]


Random float numbers generation (# rows, # cols):

In [123]:
random_floats = np.random.random((3, 4))
print(random_floats)

[[0.13457995 0.51357812 0.18443987 0.78533515]
 [0.85397529 0.49423684 0.84656149 0.07964548]
 [0.50524609 0.0652865  0.42812233 0.09653092]]


The random() method returns a random floating number between 0 and 1 [Normal Distribution]:

size = (outermost dimension [3rd], 2nd dimension [rows], 3rd dimension [cols]):

In [124]:
random_normal = np.random.normal(size=(2, 3, 2))
print(random_normal)

[[[ 0.25657045 -0.98877905]
  [-0.33882197 -0.23618403]
  [-0.63765501 -1.18761229]]

 [[-1.42121723 -0.1534952 ]
  [-0.26905696  2.23136679]
  [-2.43476758  0.1127265 ]]]


Random array generator (# rows, # cols):

In [125]:
np.random.rand(5, 2)

array([[0.79363745, 0.58000418],
       [0.1622986 , 0.70075235],
       [0.96455108, 0.50000836],
       [0.88952006, 0.34161365],
       [0.56714413, 0.42754596]])

Seed is to save the random values generated:

In [126]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [127]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Basic arithmetic operations over arrays:

In [128]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [129]:
result = arr1 + arr2
result

array([5, 7, 9])

In [130]:
result = arr1 - arr2
result

array([-3, -3, -3])

In [131]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise multiplication
result = arr1 * arr2
result

array([ 4, 10, 18])

In [132]:
result = arr1 / arr2
result

array([0.25, 0.4 , 0.5 ])

In [133]:
arr = np.array([0, np.pi/2, np.pi])
result = np.sin(arr)
result

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [134]:
result = np.exp(arr)
result

array([ 1.        ,  4.81047738, 23.14069263])

In [135]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [136]:
a + 1

array([1, 2, 3, 4, 5])

In [137]:
a * 2

array([0, 2, 4, 6, 8])

In [138]:
(10 + (a * 2)) ** 2

array([100, 144, 196, 256, 324])

Logical Operations over arrays:

In [139]:
arr = np.array([1, 2, 3, 4, 5])

# compare elements with 3
result = arr > 3
result

array([False, False, False,  True,  True])

In [140]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])

# compare elements of arr1 and arr2
result = arr1 == arr2
result

array([False,  True, False])

In [141]:
arr = np.array([1, 2, 3, 4, 5])
result = (arr > 2) & (arr < 5)
result

array([False, False,  True,  True, False])

In [142]:
arr = np.array([1, 2, 3, 4, 5])
result = (arr > 2) | (arr < 5)
result

array([ True,  True,  True,  True,  True])

In [143]:
a = np.arange(5)
b = (10 + (a * 2)) ** 2 / 100

a >= 2

array([False, False,  True,  True,  True])

In [144]:
a > b

array([False, False,  True,  True,  True])

In [145]:
a[a > b]

array([2, 3, 4])

In [146]:
a[2], a[3], a[4]

(2, 3, 4)

Some numpy functions:

In [147]:
a.min()

0

In [148]:
a.max()

4

In [149]:
a.sum()

10

In [150]:
a.mean()

2.0

Standard Deviation for the sum of array's values:

In [151]:
a.std()

1.4142135623730951

In [152]:
n = np.array([
    [12, 13, 0],
    [4, 5, 1],
    [7, 8, 2]
])

In [153]:
n.sum()

52

In [154]:
n.min()

0

In [155]:
n.max()

13

# Pandas functions and operations

Create dataframe:

In [156]:
data = [
 ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
 ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
 ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
 ['GMC', 'Acadia', 2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
 ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
columns = [
 'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
 'Transmission Type', 'Vehicle_Style', 'MSRP'
]
pd.DataFrame(data)

0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

Set header column names:

In [157]:
df = pd.DataFrame(data, columns = columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

Show first 5 rows:

In [159]:
df.head()

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

Show first 2 rows:

In [160]:
df.head(2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

Show only one column (series):

In [162]:
make_series = pd.Series(df['Make'])
make_series

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

Show specific cells based on specific criteria:

In [163]:
nissan_cars = make_series[make_series == 'Nissan']
nissan_cars

0    Nissan
4    Nissan
Name: Make, dtype: object

Show MSRP column:


In [164]:
msrp_series = pd.Series(df['MSRP'])
msrp_series

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

Find average for specific series:

In [165]:
average_msrp = msrp_series.mean()
average_msrp

30186.0

Convert currency to Euros:

In [167]:
def convert_to_euros(value):
 return value * 0.85
msrp_in_euros = msrp_series.apply(convert_to_euros)
msrp_in_euros

0     1700.0
1    23077.5
2    46741.5
3    29282.5
4    27489.0
Name: MSRP, dtype: float64

Show specific colum:

In [168]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [169]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

Show specific columns:

In [170]:
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

Add new column:

In [171]:
df['id'] = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

Show column:

In [172]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

Change values for such column:

In [173]:
df['id'] = [10, 20, 30, 40, 50]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000  10  
1         Sedan  27150  20  
2   convertible  54990  30  
3       4dr SUV  34450  40  
4        Pickup  32340  50

Delete specific column:

In [174]:
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

The numbers in the first column refer to each row (called Index):

In [175]:
df.index

RangeIndex(start=0, stop=5, step=1)

Show first row:

In [176]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

Show 2nd and 3rd rows:

In [177]:
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

change indexing type:

In [178]:
df.index = ['a', 'b', 'c', 'd', 'e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

select specific indexing:

In [179]:
df.loc[['b', 'c']]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

choose rows based on specific indeces:

In [180]:
df.iloc[[1, 2, 4]]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990  
e        Pickup  32340

To reset indexing to default:

In [181]:
df.reset_index()

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

If the old index is not needed it can simply be dropped:

In [182]:
df = df.reset_index(drop=True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

Shows NaN (null) value [which is not allowed]:

In [183]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

Doing operations on specific row:

In [184]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [185]:
df.Year

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

Logical operations:

In [186]:
df.Year >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

Filtering:

In [187]:
df[df.Year >= 2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [188]:
df[df.Make == 'Nissan']

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [191]:
df[(df.Make == 'Nissan') & (df.Year >= 2015)]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
4        Pickup  32340

String operations:

In [195]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [196]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [197]:
df['Vehicle_Style'].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

Combine multiple manipulations together:

In [198]:
df['Vehicle_Style'].str.lower().str.replace(' ', '_')

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

Perform calculations and arithmetic operations:

In [201]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [202]:
df.MSRP.min()

2000

In [203]:
df.MSRP.max()

54990

In [204]:
df.MSRP.mean()

30186.0

Describing different arithmetic details about the numeric column MSRP:

In [205]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [206]:
df.MSRP.describe().round(2)

count        5.00
mean     30186.00
std      18985.04
min       2000.00
25%      27150.00
50%      32340.00
75%      34450.00
max      54990.00
Name: MSRP, dtype: float64

For overall Dataframe:

In [207]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

Shows number of unique data:

In [208]:
df.Make.nunique()

4

In [209]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

Shows the unique values:

In [210]:
df.Year.unique()

array([1991, 2017, 2010])

Shows missing values:

In [211]:
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

Gives the sum of missing values:

In [212]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

Groups the dataframe rows by specific values, then finds the average for the grouped elements:

In [213]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

Groups the dataframe rows by specific values, then finds the minimum for the grouped elements:

In [214]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

Groups the dataframe rows by specific values, then finds the maximum for the grouped elements:

In [215]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

NumPy array return form:

In [216]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

Convert to dictionary showing it as records:

In [217]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]